# Generated by Django 4.2.29 on 2026-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baloon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
