# Generated by Django 4.2.29 on 2026-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_baloon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='baloon',
            name='manufacturer',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='baloon',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='surname',
            field=models.CharField(max_length=80),
        ),
    ]
